import { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import { LayoutContext } from '../../utils/contexts'
import styles from '../../styles/Me.module.css'
import Transactions from '../../components/Transactions'
import { CircularProgress } from '@mui/material'
import TransferEther from '../../components/TransferEther'
import DataTableContainer from '../../components/DataTableContainer'

const Me: NextPage = () => {
  const {
    currentAddress,
    currentBalance,
    ethereum,
    checkingWalletConnection
  } = useContext(LayoutContext)

  return (
    <div>
      <Head>
        <title>Me - Stepzen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '2rem' }}>
        {
          checkingWalletConnection?
            <CircularProgress />
          :
            ethereum?
              currentAddress && currentBalance?
                <>
                  <div>
                    <h2>Your Account: {currentAddress}</h2>
                    <div>
                      <b>Balance:</b>
                      {currentBalance} Eth
                      <i>(This is the selected metamask account balance)</i>
                    </div>
                  </div>
                  <div className={styles.sectionsContainer}>
                    <div className={styles.leftSection}>
                      <div className={styles.transactionFormContainer}>
                        <TransferEther />
                      </div>
                    </div>
                    <div className={styles.rightSection}>
                      <DataTableContainer address={currentAddress} />
                    </div>
                  </div>
                </>
              :
                <div>
                  Connect to Metamask
                </div>
            :
              <div>
                <a
                  href="https://metamask.io/download/"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: 'blue' }}
                >
                  Install MetaMask
                </a>
              </div>
        }
      </main>
    </div>
  )
}

export default Me