import { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent, useContext, useState } from 'react'
import { LayoutContext } from '../../utils/contexts'

const Accounts: NextPage = () => {
  const { currentAccount } = useContext(LayoutContext)
  const [addressTo, setAddressTo] = useState('')
  const [amount, setAmount] = useState(0.001)
  const [message, setMessage] = useState('')
  
  const onAddressToChange = (ev: ChangeEvent<HTMLInputElement>) => {
    setAddressTo(ev.target.value)
  }

  const onAmountChange = (ev: ChangeEvent<HTMLInputElement>) => {
    //@ts-ignore
    setAmount(ev.target.value)
  }

  const onMessageChange = (ev: ChangeEvent<HTMLInputElement>) => {
    setMessage(ev.target.value)
  }

  const onFormSubmit = () => {
    console.log('addressto', addressTo)
    console.log('amount', amount)
    console.log('message', message)
  }

  return (
    <div>
      <Head>
        <title>Me - Stepzen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Your Account: {currentAccount}</h1>

        </div>
        <div>
          <h3>Transfer</h3>
          <form onSubmit={onFormSubmit}>
            <input type='text' name='addressTo' placeholder='Receiver Address' value={addressTo} onChange={onAddressToChange}/>
            <input type='number' step={0.001} name='amount' value={amount} onChange={onAmountChange}/>
            <input type='text' placeholder='Message' value={message} onChange={onMessageChange}/>
            <input type='submit' />
          </form>
        </div>

        
      </main>
    </div>
  )
}

export default Accounts