import TextField from '../components/TextField'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent, useState } from 'react'
// import { Search, SearchIconWrapper, StyledInputBase } from '../components/SearchInput'
import SearchIcon from '@mui/icons-material/Search'
import styles from '../styles/Home.module.css'
import NFTCardList from '../components/NFTCardList'

const Home: NextPage = () => {
  const [search, setSearch] = useState('')
  const [fetchResult, setFetchResult] = useState(false)

  const onSearchChange = (ev: ChangeEvent<HTMLInputElement>) => {
    setSearch(ev.target.value)
  }

  const onSearch = () => {
    setFetchResult(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroBanner}>
          <h1 className={styles.title}>
            Welcome to NFT Explorer
          </h1>

          <div className={styles.description}>
            <span className={styles.searchContainer}>
              <TextField
                placeholder='Search Collection, name...'
                value={search}
                onChange={onSearchChange}
              />
              <span
                className={styles.searchIconContainer}
                onClick={onSearch}
              >
                <SearchIcon/>
              </span>
            </span>
          </div>
        </div>

        <div className={styles.searchResultContainer}>
          <NFTCardList
            search={search}
            fetchResult={fetchResult}
            setFetchResult={setFetchResult}
          />
        </div>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
